# Generated by Django 5.0.4 on 2024-05-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], default='M', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=255),
        ),
    ]
